### ISSUE TITLE
pH Scale: Basics - Publish 1.6 with PhET-iO Upgrades

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/ph-scale-basics#49]
As part of the "batch release" milestone https://github.com/orgs/phetsims/projects/44, publish pH Scale:Basics, for brands=phet,phet-io.

**Comment by pixelzoom** [comment]
Unassigning until this becomes a priority.

**Comment by pixelzoom** [comment]
I'm going to track ph-scale and ph-scale-basics 1.6 release together in https://github.com/phetsims/ph-scale/issues/236, since they will go through QA and be published together.  So closing this issue.
