### ISSUE TITLE
pH Scale: Basics - Publish 1.6 with PhET-iO Upgrades

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale-basics#51]
... at the same time as:
* https://github.com/phetsims/ph-scale/issues/236

See that issue for history of the publication timeline.

**Comment by zepumph** [comment]
Please see https://github.com/phetsims/ph-scale/issues/280 as we get ph-scale-basics ready for next rc (rc.2)

**Comment by zepumph** [comment]
ph-scale-basics:

[phetsims/qa#893](https://github.com/phetsims/qa/issues/893)
https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.0-rc.2/

**Comment by samreid** [comment]
@matthew-blackman and I published 1.6.0 today.  Nice work everyone!  @pixelzoom anything to check or review?

**Comment by pixelzoom** [comment]
👍🏻

**Comment by pixelzoom** [comment]
For anyone else who is keeping metrics... Elapsed time between for the QA process was 54 days.
