### ISSUE TITLE
Assertion failed: Impossible set state from iterate; unset state

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/ph-scale-basics#53]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.1

**Browser**
safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/873, I was unable to load a saved custom wrapper from studio 1.5 into studio 1.6. 

**Steps to reproduce**
1. Open Studio 1.5 and press the Save button
2. Open Studio 1.6 and attempt to load the saved custom wrapper

**Visuals**
<img width="1228" alt="Screenshot 2023-01-19 at 8 57 33 AM" src="https://user-images.githubusercontent.com/87318828/213463537-a2e20b2a-8185-4624-8c87-b7bbe8abe3cf.png">

**Comment by zepumph** [comment]
Interesting. I'm not sure I totally understand it, but I'm pretty sure it is fixed on master since https://github.com/phetsims/phet-io-sim-specific/commit/45af541aa8074260b796dc0d148387032baec4a1

Would you mind testing 1.5 against master (after a pull-all), and see if you have any luck? Thanks!

**Comment by zepumph** [comment]
I was really surprised to not see quite a few rules that were in ph-scale but not in basics. @samreid, could you please take another look here? I added one for updating solute names, but I was generally out of the ph-scale migration rule loop, and I don't know if there was a specific reason to omit many of these in basics.

**Comment by zepumph** [comment]
- [ ] As part of this issue, let's do another large "copy paste" from phScale. Then apply our "hack" again to note rules that don't do anything.

**Comment by pixelzoom** [comment]
@zepumph said:
> I was really surprised to not see quite a few rules that were in ph-scale but not in basics.  ...

I moved review of ph-scale-basics-migration-rules.ts to https://github.com/phetsims/ph-scale-basics/issues/56.

**Comment by zepumph** [comment]
migration rule updates have been cherry picked. @samreid and @zepumph can confirm that ph-scale-basics will not fail when migrating in our local builds. We will confirm with RC.2 and close.

**Comment by zepumph** [comment]
Migration is success and error free in the new RCs. Closing
