### ISSUE TITLE
Batch Migration Failure

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale-basics#54]
For https://github.com/phetsims/qa/issues/873. Seen with Win 11 Chrome.
When trying to do a batch migration, none of the files were migrated and this error appeared in the console. I'm not sure what caused it.
<img width="960" alt="migrationfailed" src="https://user-images.githubusercontent.com/41024075/213549285-042e9d83-9407-4a3a-9c7d-f240570143e4.png">

**Comment by Nancy-Salpepi** [comment]
I believe this is the same as https://github.com/phetsims/ph-scale-basics/issues/53

**Comment by zepumph** [comment]
Yes thanks, closing as a duplicate of https://github.com/phetsims/ph-scale-basics/issues/53
