### ISSUE TITLE
Check for missing rules in ph-scale-basics-migration-rules.ts 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale-basics#56]
In https://github.com/phetsims/ph-scale-basics/issues/53#issuecomment-1397341519, @zepumph said:

> I was really surprised to not see quite a few rules that were in ph-scale but not in basics. @samreid, could you please take another look here? I added one for updating solute names, but I was generally out of the ph-scale migration rule loop, and I don't know if there was a specific reason to omit many of these in basics.

**Comment by pixelzoom** [comment]
Here are the "missing rules" that seem relevant to ph-scale-basics. 

This rule may have been omitted because this is a 1-screen sim. But this Property is still present in the Studio tree, as a linked element at `phScaleBasics.macroScreen.nameProperty`.
```
    new ConvertToStringsStateForLocale( 'phScale.macroScreen.nameProperty', 'phScale.general.model.strings.phScale.screen.macroStringProperty', stringsStatePhetioID ),
```

These 2 rules were add to ph-scale-migration-rules.ts on 1/20 by @zepumph, but were not added to ph-scale-basics-overrides.ts:
```
    new TandemFragmentDelete( 'soundManager.extraSoundEnabledProperty' ),
    new TandemFragmentDelete( 'soundManager.enabledProperty' )
```

All of the other rules that I reviewed are specific to the Micro screen or My Solution screen, which do not appear in ph-scale-basics.

**Comment by pixelzoom** [comment]
Another comment about this addition to ph-scale-migration-rules.ts by @zepumph ...

```
    new TandemFragmentDelete( 'soundManager.extraSoundEnabledProperty' ),
    new TandemFragmentDelete( 'soundManager.enabledProperty' )
```

There is no documentation, and no link to an issue.  I had to go looking through commits.  After having fixed up the migration file to include comments and GitHub issue numbers, it's frustrating that the first additions have no documentation.  This does not bode well for readability and maintanance of migration rules.

**Comment by pixelzoom** [comment]
Another comment about this addition to ph-scale-migration-rules.ts by @zepumph ...

```
    new TandemFragmentDelete( 'soundManager.extraSoundEnabledProperty' ),
    new TandemFragmentDelete( 'soundManager.enabledProperty' )
```

There is no documentation, and no link to an issue.  I had to go looking through commits.  After having spent considerable effort to improve the migration file by including comments and GitHub issue numbers, it's frustrating that the first additions have no documentation.  And I see that this was done in multiple migration-rules.ts files. This does not bode well for readability and maintanance of migration rules.

**Comment by pixelzoom** [comment]
These missing rules:

```
    new TandemFragmentDelete( 'soundManager.extraSoundEnabledProperty' ),
    new TandemFragmentDelete( 'soundManager.enabledProperty' )
```

... were causing the failure in https://github.com/phetsims/ph-scale/issues/271#issuecomment-1400604859. Added in the above commit.

**Comment by pixelzoom** [comment]
@zepumph @samreid and I discussed. 

This missing rule is still a problem. Why is this not being identified? 

```
new ConvertToStringsStateForLocale( 'phScale.macroScreen.nameProperty', 'phScale.general.model.strings.phScale.screen.macroStringProperty', stringsStatePhetioID ),
```

**Comment by samreid** [comment]
On hold until ph-scale is completed.

**Comment by zepumph** [comment]
Cherry picks for migration rules in basics has been done. I confirmed that there are no missing (erroring) or superfluous rules. Closing
