### ISSUE TITLE
branch: descriptionTooling

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/ph-scale-basics#59]
A branch with changes for https://github.com/phetsims/joist/issues/941. This is a similar to the idea  proposed there, but the code is more integrated with the sim instead of using a "plugin" strategy. Instead of using PhET-iO, there is a high level `ScreenDescriptionLogic` that has access to the model and view of the screen to create the necessary descriptions.

Some benefits:
- Doesn't use PhET-iO or PhET-iO ids.
- Able to use TypeScript.
- Easier to extend/reuse code as needed for "suites" of sims.
- Easier to make the description logic modular, can easily break it into multiple files.
- No need to develop additional tooling/user interfaces.

Some drawbacks:
- More changes needed in sim code to access the components needed to describe the sim.
- TypeScript and other changes that make the code more maintainable will make it more difficult for designers to work with.

**Comment by pixelzoom** [comment]
To the list of drawbacks, I would add:

* Requires many things to be made `public` solely for description.

**Comment by terracoda** [comment]
Add to list of benefits:
- Designers may find it easier to work in JSON than TS or JS files to define parameters and description strings.
     - If it is reasonable and workable for designers to create descriptions in JSON files, descriptions designs would be under the same version control as other sim code which I think would be nice.
- Regarding file break up and organization, I mentioned to @jessegreenberg that one way to break up the files, could be to align the files to our design process. For example, we have a file for object names and help text, a second file for the dynamic screen/scene summary, and then as we go forward we add additional files for the remaining State Descriptions, and potentially break up Responsive Descriptions (Object and Context responses) by interactive object? Not sure if that's the best way to organize things, but it organizes things from essentials or basic descriptions to full description in a way that makes sense to me.

**Comment by jessegreenberg** [comment]
I have deleted this branch, we do not need to keep it to discuss ideas for https://github.com/phetsims/joist/issues/941
