### ISSUE TITLE
Incorrect terminology in descriptions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale-basics#62]
Related to #60 ...  Solute, solvent, and solution are important terms in a pH chemistry sim.  The current descriptions are using the term "solution" incorrectly in a few places.  For example:

"solution dropper" - the dropper contains solute, not solution. Solution is what is in the beaker, and what comes out of the drain faucet.

"Add solution to beaker" - solute (via the dropper) or solvent (via the water faucet) are what can be added to the beaker. Solution is the combination of solute and solvent that is in the beaker.

**Comment by arouinfar** [comment]
I think it would be helpful for @Nancy-Salpepi to weigh in here, but I think the way we characterize the liquid in the dropper as a "solute" in the code is not entirely correct. Many of the dropper contents contain water, and are by definition solutions. I understand why we refer to them as solutes from a model perspective, but it can be problematic for learners to hear them referred to as "solutes".

**Comment by Nancy-Salpepi** [comment]
As @arouinfar said, the items in the dropper contain water and are solutions. The pH value is measuring the concentration of hydrogen ions in that solution.  When water is added from the faucet, the solution is being diluted, the concentration of  hydrogen ions changes, and thus the pH value changes.

some examples:
Milk: ~87% water
Spit: ~99% water
Soda: 95% water
Orange Juice: ~90% water
Hand soap: water is the first ingredient listed on mine
Battery acid: contains sulfuric acid + water
Blood: the plasma portion is ~92% water

**Comment by pixelzoom** [comment]
Thanks @Nancy-Salpepi, sounds like we can close this issue.
